title: AWSome Insights
author: Prasoon Dwivedi
email: dwivedi.prasoon@gmail.com
description: >
  A personal blog on my AWS Cloud journey, architecture practices, and DevOps insights.
baseurl: ""
url: "https://dwivedi-prasoon.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: true
